### ISSUE TITLE
Download modified files from LS on script startup

### ISSUE THREAD

**Issue by leahtard** [af19/grunt-lemonsync#6]
On startup, the python version of this script will download any changes from LS. Can this version mimic the same functionality? For our typical use case, we want to ensure we are downloading any potential changes our client has made within the LS admin interface before pushing back up (and potentially overriding their changes).

**Comment by leahtard** [comment]
Thanks for this Amir. I gave it a try and I was able to download the theme with the new command. My only feedback would be that it currently enforces that all of your theme files sit in a "theme" folder. This isn't currently the folder structure we use. Thanks again for your work on this!

**Comment by af19** [comment]
Great! 

I think adding an option for setting the theme folder would be good.
